export const dataList = [
  {
    id: 1,
    name: "Rishabh",
    email: "test@gmail.com",
    phone: "899456870596",
    username: "rishabh",
    website: "www.test.com",
  },
  {
    id: 2,
    name: "Sagar",
    email: "saagr@gmail.com",
    phone: "9638527415",
    username: "sagar",
    website: "www.developer.com",
  },
  {
    id: 3,
    name: "Pavan",
    email: "pavan@gmail.com",
    phone: "788589964522",
    username: "pavan",
    website: "www.dev.com",
  },
  {
    id: 4,
    name: "Kunal",
    email: "kunal@gmail.com",
    phone: "0456451115",
    username: "kunal",
    website: "www.kkk.com",
  },
  {
    id: 5,
    name: "Pavan",
    email: "pavan@gmail.com",
    phone: "788589964522",
    username: "pavan",
    website: "www.dev.com",
  },
  {
    id: 6,
    name: "Kunal",
    email: "kunal@gmail.com",
    phone: "0456451115",
    username: "kunal",
    website: "www.kkk.com",
  },
  {
    id: 7,
    name: "Pavan",
    email: "pavan@gmail.com",
    phone: "788589964522",
    username: "pavan",
    website: "www.dev.com",
  },
  {
    id: 8,
    name: "Kunal",
    email: "kunal@gmail.com",
    phone: "0456451115",
    username: "kunal",
    website: "www.kkk.com",
  },

  {
    id: 9,
    name: "Kunal",
    email: "kunal@gmail.com",
    phone: "0456451115",
    username: "kunal",
    website: "www.kkk.com",
  },
  {
    id: 10,
    name: "Pavan",
    email: "pavan@gmail.com",
    phone: "788589964522",
    username: "pavan",
    website: "www.dev.com",
  },
  {
    id: 11,
    name: "Kunal",
    email: "kunal@gmail.com",
    phone: "0456451115",
    username: "kunal",
    website: "www.kkk.com",
  },
  {
    id: 12,
    name: "Pavan",
    email: "pavan@gmail.com",
    phone: "788589964522",
    username: "pavan",
    website: "www.dev.com",
  },
  {
    id: 13,
    name: "Kunal",
    email: "kunal@gmail.com",
    phone: "0456451115",
    username: "kunal",
    website: "www.kkk.com",
  },
  {
    id: 14,
    name: "Pavan",
    email: "pavan@gmail.com",
    phone: "788589964522",
    username: "pavan",
    website: "www.dev.com",
  },

  {
    id: 15,
    name: "Kunal",
    email: "kunal@gmail.com",
    phone: "0456451115",
    username: "kunal",
    website: "www.kkk.com",
  },
];
